swagger: "2.0"
info:
  title: Rostercontrol
  version: 1.0.0
  description: Vali oma lemmik töötaja
paths:
  /worker:
    get:
      tags:
        - Worker
      responses:
        "200":
          description: Returns a list of Workers
          schema:
            type: array
            items:
              type: string
          examples:
            application/json:
              - Maria
              - Sharia
              - Daria
      summary: Get all the <workers> in API
      description: Return all Workers that are registered in API
    post:
      tags:
        - Worker
      parameters:
        - name: body
          description: The <Worker> that is to be created.
          schema:
            $ref: "#/definitions/new-Worker"
          in: body
          required: true
      responses:
        "201":
          description: Send 201 when <Worker> is successfully added to the database
          schema:
            $ref: "#/definitions/new-Worker"
          examples:
            application/json:
              FirstName: NewFirstName
              LastName: NewLastName
              Workload: NewWorkload
              IsActive: NewIsActive
              RoleName: NewWorkload
        "400":
          description: "Missing some parameter, please review your request data"
          schema:
            $ref: "#/definitions/error"
      summary: Create a new <Worker> into the app
      description: "Creates a new <Worker> instance with its required details, for further usage."
  "/worker/{WorkerID}":
    get:
      tags:
        - Worker
      responses:
        "200":
          description: Return details of Worker
        "404":
          description: Worker with this ID not found
          schema:
            $ref: "#/definitions/error"
      operationId: WorkerID
      summary: Get the full details of a Worker
      description: Will return all details of a given <Worker> based on WorkerID given.
    put:
      tags:
        - Worker
      parameters:
        - name: body
          description: Contains new data to be changed in the specified Worker
          schema:
            $ref: "#/definitions/new-Worker"
          in: body
          required: true
      responses:
        "201":
          description: |
            Returns 201 upon successful modification of Worker
          schema:
            $ref: "#/definitions/new-Worker"
          examples:
            application/json:
              - FirstName: ""
                LastName: ""
                Workload: ""
                IsActive: ""
                RoleName: ""
        "400":
          description: Returns 400 when one or multiple required parmeters are missing
          schema:
            $ref: "#/definitions/error"
          examples:
            application/json:
              - error: "cannot change info, because some parameter missing."
        "404":
          description: "Returns 404 when Worker that is to be modified, is not found by the given WorkerID"
          schema:
            $ref: "#/definitions/error"
          examples:
            application/json:
              - error: Worker not found
    delete:
      tags:
        - Worker
      parameters:
        - name: body
          description: ID of <Worker> to be removed from the app
          schema:
            $ref: "#/definitions/delete-Worker"
          in: body
          required: true
      responses:
        "204":
          description: Returns  "No content" when removal of <Worker> is sucess
          schema:
            $ref: "#/definitions/error"
          examples:
            application/json:
              - error: No Content
        "404":
          description: "Returns error, when <Worker> with specified ID does not exist"
          schema:
            $ref: "#/definitions/error"
          examples:
            application/json:
              - error: ID not found
      summary: Delete a <Worker> from the app
      description: Deletes an entry from the app
    parameters:
      - name: WorkerID
        description: ID of Worker
        in: path
        required: true
        type: string
  /shift:
    get:
      tags:
        - Shift
      responses:
        "200":
          description: Returns a list of Shifts
          schema:
            type: array
            items:
              type: string
          examples:
            application/json:
              - StartTime: ""
                EndTime: ""
              - StartTime: ""
                EndTime: ""
      summary: Get all the <shift> in API
      description: Return all Shifts that are registered in API
    post:
      tags:
        - Shift
      parameters:
        - name: body
          description: The <Shift> that is to be created.
          schema:
            $ref: "#/definitions/new-Shift"
          in: body
          required: true
      responses:
        "201":
          description: Send 201 when <Shift> is successfully added to the database
          schema:
            $ref: "#/definitions/new-Shift"
          examples:
            application/json:
              ShiftDate: "2000-01-31"
              StartTime: "10:00:00"
              EndTime: "18:00:00"
      summary: Create a new <Shift> into the app
      description: "Creates a new <Shift> instance with its required details, for further usage."
  "/shift/{ShiftID}":
    get:
      tags:
        - Shift
      responses:
        "200": {}
        "404":
          schema:
            $ref: "#/definitions/error"
      summary: Get the full details of a Shift
      description: Will return all details of a given <Shift> based on ShiftID given.
    put:
      tags:
        - Shift
      parameters:
        - name: body
          description: Contains new data to be changed in the specified Worker
          schema:
            $ref: "#/definitions/new-Shift"
          in: body
          required: true
      responses:
        "201":
          description: |
            Returns 201 upon successful modification of Shift
          schema:
            $ref: "#/definitions/new-Shift"
          examples:
            application/json:
              - ShiftDate: ""
                StartTime: ""
                EndTime: ""
        "400":
          description: Returns 400 when one or multiple required parmeters are missing
          schema:
            $ref: "#/definitions/error"
          examples:
            application/json:
              - error: "cannot change info, because some parameter missing."
        "404":
          description: "Returns 404 when Shift that is to be modified, is not found by the given ShiftID"
          schema:
            $ref: "#/definitions/error"
          examples:
            application/json:
              - error: Shift not found
    delete:
      tags:
        - Shift
      responses:
        "204":
          description: Returns  "No content" when removal of <Shift> is sucess
          schema:
            $ref: "#/definitions/error"
          examples:
            application/json:
              - error: No Content
        "404":
          description: "Returns error, when <Worker> with specified ID does not exist"
          schema:
            $ref: "#/definitions/error"
          examples:
            application/json:
              - error: ID not found
      description: Deletes an entry from the app
    parameters:
      - name: ShiftID
        description: ID of Shift
        in: path
        required: true
        type: string
  /schedule:
    get:
      tags:
        - Schedule
      responses:
        "200":
          description: Returns a list of Schedules
          schema:
            type: string
          examples:
            application/json: "                ScheduleName: Janauar\r\n                StartDate: \"2026-01-01\"\r\n                EndDate: \"2026-01-31\"\r\n              - ScheduleName: Janauar\r\n                StartDate: \"2026-01-01\"\r\n                EndDate: \"2026-01-31\"\r\n"
      summary: Get all the <schedule> in API
      description: Return all Schedules that are registered in API
    post:
      tags:
        - Schedule
      responses:
        "201":
          description: "Send 201 when <Schedule> is successfully added to the database\r\n"
          schema:
            type: array
            items:
              type: string
          examples:
            application/json: "              ScheduleName: NewScheduleName\r\n              StartDate: \"2026-01-01\"\r\n              EndDate: \"2026-01-29"
        "400":
          description: "Missing some parameter, please review your request data"
          schema:
            $ref: "#/definitions/error"
          examples:
            application/json:
              - error: ""
      description: The <Schedule> that is to be created.
  /sessions:
    post:
      tags:
        - Users
        - Auth
      parameters:
        - name: body
          description: Data of the user
          schema:
            $ref: "#/definitions/login-User"
          in: body
          required: true
      responses:
        "200":
          description: Returns selected user data for site functioning
          schema:
            $ref: "#/definitions/loggedin-User"
          examples:
            application/json:
              - UserID: ""
                DisplayName: "1"
                EmailAddress: w
                IsAdmin: false
        "400":
          description: Returns bad request when parameters are missing
          schema:
            $ref: "#/definitions/error"
          examples:
            application/json:
              - error: Missing parameter for logging in
        "401":
          description: Returns 401 Unauthorized when incorrect data is inserted.
          schema:
            $ref: "#/definitions/error"
          examples:
            application/json:
              - error: Password mismatch
        "404":
          description: Returns 404 error when user is not found
          schema:
            $ref: "#/definitions/error"
          examples:
            application/json:
              - error: User not found
      summary: Make session get cookie
  "/schedule/{ScheduleID}":
    get:
      tags:
        - Schedule
      responses:
        "200":
          description: 200 for getting all the details of the Schedule
          schema:
            $ref: "#/definitions/new-Schedule"
        "404":
          description: Schedule with given ID not found
          schema:
            $ref: "#/definitions/error"
          examples:
            application/json:
              - error: "0"
      operationId: ScheduleID
      summary: Get the full details of a Schedule
      description: Will return all details of a given <Schedule> based on ScheduleID given.
    put:
      tags:
        - Schedule
      responses:
        "201":
          description: "Returns 201 upon successful modification of Schedule\r\n"
          schema:
            $ref: "#/definitions/new-Schedule"
          examples:
            application/json: "\r\n              - ScheduleName: 3g\r\n                StartDate: \"2026-02-01\"\r\n                EndDate: \"2026-03-02\"\r\n"
        "400":
          description: "Returns 400 when one or multiple required parmeters are missing\r\n"
          schema:
            $ref: "#/definitions/error"
          examples:
            application/json: "error: \"cannot change info, because some parameter missing.\"\r\n"
        "404":
          description: "Returns 404 when Schedule that is to be modified, is not found by the given ScheduleID"
          schema:
            $ref: "#/definitions/error"
          examples:
            application/json: "application/json:\r\n  error: \"Schedule not found\""
      operationId: ScheduleID
      description: Contains new data to be changed in the specified Schedule
    delete:
      tags:
        - Schedule
      responses:
        "204":
          description: Returns  "No content" when removal of <Schedule> is success
          schema:
            $ref: "#/definitions/delete-Schedule"
          examples:
            application/json: "error: No Content\r\n"
        "404":
          description: "Returns error, when <Schedule> with specified ID does not exist"
          schema:
            $ref: "#/definitions/delete-Schedule"
          examples:
            application/json: "error: ID not found\r\n"
      operationId: ScheduleID
      summary: Delete a <Schedule> from the app
      description: Deletes an entry from the app
    parameters:
      - name: ScheduleID
        description: ID of Schedule
        in: path
        required: true
        type: string
definitions:
  error:
    title: Root Type for error
    description: ""
    type: object
    properties:
      error:
        type: string
    example:
      error: Error message
  delete-Worker:
    title: Root Type for delete-Worker
    description: ""
    type: object
    properties:
      WorkerID:
        type: string
    example:
      WorkerID: 5f9b9e90-cec3-11f0-b43f-901b0eec5991
  new-Worker:
    title: Root Type for new-Worker
    description: ""
    required:
      - FirstName
      - LastName
      - Workload
      - IsActive
      - RoleName
    type: object
    properties:
      FirstName:
        type: string
      LastName:
        type: string
      Workload:
        type: string
      IsActive:
        type: string
      RoleName:
        description: ""
        type: string
    example:
      FirstName: NewFirstName
      LastName: NewLastName
      Workload: NewWorkload
      IsActive: "true"
      RoleName: NewRoleName
  new-Shift:
    description: ""
    required:
      - ShiftDate
      - StartTime
      - EndTime
    type: object
    properties:
      ShiftDate:
        description: ""
        type: string
      StartTime:
        description: ""
        type: string
      EndTime:
        description: ""
        type: string
    example:
      ShiftDate: NewShiftDate
      StartTime: NewStartTime
      EndTime: NewEndTime
  delete-Shift:
    description: ""
    required:
      - ShiftID
    type: object
    properties:
      ShiftID:
        description: ""
        type: string
    example:
      ShiftID: 5f9b9e90-cec3-11f0-b43f-901b0eec5991
  new-Schedule:
    description: ""
    required:
      - ScheduleName
      - StartDate
      - EndDate
    type: object
    properties:
      ScheduleName:
        description: ""
        type: string
      StartDate:
        description: ""
        type: string
      EndDate:
        description: ""
        type: string
    example:
      ScheduleName: NewScheduleName
      StartDate: NewStartDate
      EndDate: NewEndDate
  delete-Schedule:
    description: ""
    required:
      - ScheduleID
    type: object
    properties:
      ScheduleID:
        description: ""
        type: string
    example:
      ScheduleID: 5f9b9e90-cec3-11f0-b43f-901b0eec5991
  login-User:
    title: Root Type for login-User
    description: Data that the User provides upon an attempt to login
    type: object
    properties:
      LoginEmail:
        type: string
      LoginPassword:
        type: string
    example:
      LoginEmail: asfa
      LoginPassword: "1244"
  loggedin-User:
    title: Root Type for loggedin-User
    description: "Data of the user, that is returned upon successful new session, or reauthenticating old session"
    type: object
    properties:
      UserID:
        type: string
      DisplayName:
        type: string
      EmailAddress:
        type: string
      IsAdmin:
        type: boolean
    example:
      UserID: 111231saf-12312 jne
      DisplayName: aff
      EmailAddress: a@afa.com
      IsAdmin: false
